### ISSUE TITLE
Error on import

### ISSUE THREAD

**Issue by fillidiabolli** [simon50keda/ConverterPIXWrapper#9] opened 2024-04-19 22:04 UTC
is there a work round for the following error "ConverterPIX crashed or encountered error! Standard output returned" Tried reinstalling blender and get the same error on numerous mods.

**Comment by 2sail2you** [comment] 2024-04-19 23:21
Same,
The tool worked perfeclty since today, can't import any SCS Files. Getting the '' Crashed'' and ''Can't load TOBJ/DDS Files''
Tried reinstalling Blender too but didn't do anything. 
Is there any way to fix this issue?
Thanks in advance

**Comment by tasnimulamin12** [comment] 2024-04-20 14:04
Suddenly tools crash from today any solution?

**Comment by ridhvvn** [comment] 2024-04-20 21:35
same error on blender 3.2, ets1.49 game files

**Comment by PrincexBijoy** [comment] 2024-04-20 21:53
DDS file is corrupt ,🤢 Can't import any scs files

**Comment by Asif1177** [comment] 2024-04-21 07:41
Dear glitc hub please fix this problm. My most important work is stoped for this kind of problm. Please fix it fast

**Comment by V-Mourtos** [comment] 2024-04-21 14:36
I've been having the same issue for the last couple of days. I think files that use textures from the base game seem to have this issue.

**Comment by felipedorea** [comment] 2024-04-21 14:39
I have a issue that i can´t import the Mercedes Actros 2014, all of another trucks works perfectly, but the mercedes appear this error:  "ConverterPIX crashed or encountered error! Standard output returned" ... I tried all possibilities and nothing work.

**Comment by Nirobislam01** [comment] 2024-04-21 15:03
anyone have fix file for this problem?

**Comment by Sadbeatz** [comment] 2024-04-21 23:24
I've been having the same issue since yesterday day.

**Comment by arinalao** [comment] 2024-04-22 07:49
![Screenshot_42](https://github.com/simon50keda/ConverterPIXWrapper/assets/167748977/f8696f2b-a0e7-4c52-aca9-0a09debae67d)
the same thing happened to me

**Comment by 020417** [comment] 2024-04-22 17:35
Mesmo erro de todos aqui!

![erro](https://github.com/simon50keda/ConverterPIXWrapper/assets/167803417/b150a8bc-14f8-4fd1-ab9b-084716a11545)

**Comment by small2998** [comment] 2024-04-23 07:22
Hi. I'm experiencing the same issue here. Running ets2 1.49 files. It's was working well all along and suddenly showed up that issue.

**Comment by small2998** [comment] 2024-04-23 18:33
Hi. Please refer to the following link, as it seems that there is an issue with converter pix wrapper at the moment... https://youtu.be/fY4sVKlzPKI?si=jVDjd6QAFUPc2Z16

**Comment by mwl4** [comment] 2024-04-23 22:03
It should be fixed now.

**Comment by Asif1177** [comment] 2024-04-24 06:52
> This issue is most probably consequence of converter_pix update, I notified the author, so once he resolves it, I will let you all know.

thanks men .its fix now

**Comment by simon50keda** [comment] 2024-04-26 06:49
@fillidiabolli I deleted duplicate threads, so please report the problem here again with the log attached, thx.

**Comment by MrSloky** [comment] 2024-04-26 10:34
Hi, i'm using Blender 4.1, the latest version of scs tools and pix wrapper.

But when i'm importing some models, nothing appends and some errors appears on log.
Have you any idea of the issue?

![image](https://github.com/simon50keda/ConverterPIXWrapper/assets/168185146/294bcbb2-876e-453f-8162-34a0bc1b64ae)

[ErrorLog.txt](https://github.com/simon50keda/ConverterPIXWrapper/files/15129389/ErrorLog.txt)

**Comment by AmirMahdaviAM** [comment] 2024-04-26 10:52
> Hi, i'm using Blender 4.1, the latest version of scs tools and pix wrapper.
> 
> But when i'm importing some models, nothing appends and some errors appears on log. Have you any idea of the issue?
> 

Blender 3.6+ are not fully supported and buggy
Use blender 3.3 or 3.6 lts version and test again

**Comment by avengerx** [comment] 2024-04-26 11:51
I have fresh installed extension, blender 4.1.0, and I'm not reproducing _this_ issue, at least.

**Comment by Asif1177** [comment] 2024-04-26 11:53
> I have fresh installed extension, blender 4.1.0, and I'm not reproducing _this_ issue, at least.

Blender 4.1 not support try 3.0

**Comment by avengerx** [comment] 2024-04-26 13:18
3.6.11 (LTS) seems to be working better, at least.

**Comment by Riipperino** [comment] 2024-05-15 15:07
2.92 still not working here 
![2790e07faa992cb01501c6ab3fabc879](https://github.com/simon50keda/ConverterPIXWrapper/assets/13180128/2d24448b-d19b-4c4f-86df-df0651d11ba6)

**Comment by avengerx** [comment] 2024-05-15 17:18
I think you forgot to specify extra data files.
try adding the game you're trying's base.scs file (ATS or ETS2). You'll see this in the import dialog:
![image](https://github.com/simon50keda/ConverterPIXWrapper/assets/808610/aafae81e-9629-45b1-8c07-de344d50738f)
As I just said in previous post, 3.6.11 worked like a charm.

**Comment by felipedorea** [comment] 2024-05-16 10:16
Hi, im using blender 3.6.11 and have the same error, i specified extra files, base.scs and base_vehicle.scs cause i want to modify trucks, but i cant import any truck, all times occur this error, what can i be making wrong?

**Comment by avengerx** [comment] 2024-05-16 20:43
@felipedorea if you have an error message that doesn't match the one in the beginning of this issue, why don't you create a new one? There must be an error or warning displaying in your logs. Without them it's pretty hard to tell what's wrong.

**Comment by mwl4** [comment] 2024-05-19 12:12
@Riipperino @felipedorea there are more game archives now than just base.scs. You should add to extra archives: base.scs, base_share.scs, base_vehicle.scs at least. What I do is selecting all archives from game directory and add them as extra archives.

Cheers

**Comment by felipedorea** [comment] 2024-05-19 16:27
> @Riipperino @felipedorea there are more "base" game archives now than just base.scs. You should add to extra archives: base.scs, base_share.scs, base_vehicle.scs at least. What I do is selecting all archives from game directory and add them as extra archives.
> 
> Cheers

I tried it. Same error!

**Comment by mwl4** [comment] 2024-05-20 12:42
@felipedorea What model file you are trying to load? Give some reproduction steps.

**Comment by felipedorea** [comment] 2024-05-20 13:17
First i extracted the base.scs, base_vehicle.scs, base_share.scs and def.scs with the scs extractor updated for 1.50 downloaded from scs modding tools website... I´m using blender 3.6.11 and i installed all dependencies, till here normal... But when i try to import any truck have this error... My steps was: 

1 - set base.scs, base_vehicle.scs and base_share.scs to extra archives;
2 - click import;
3 - select volvo FH12 2016 - Truck that i want edit 

This was my steps, and happen with any trucks, am i doing something wrong?

**Comment by mwl4** [comment] 2024-05-20 14:02
@felipedorea Do not use scs_extractor in this case at all. Just add base.scs, base_vehicle.scs and base_share.scs and other archives to extra archives:
![image](https://github.com/simon50keda/ConverterPIXWrapper/assets/5429225/858e8d2b-33a7-4385-997e-56eacfb03f42)
click "Import SCS...", navigate to /vehicle/truck/volvo_fh16_2012, select truck.pmg, click Ok, here is what you should get:
![image](https://github.com/simon50keda/ConverterPIXWrapper/assets/5429225/bb6dd839-9b7c-458e-9699-0d6270a6dea0)

ETS2 game archives do not contain "FH12 2016 - Truck", do you import some game modification?

**Comment by felipedorea** [comment] 2024-05-20 14:26
Yeah, it´s this FH16 2012, i mistaken the correct name kkk sorry, but it´s exactly this truck! Ty for help, i will try it.

**Comment by felipedorea** [comment] 2024-05-21 01:57
> @felipedorea Do not use scs_extractor in this case at all. Just add base.scs, base_vehicle.scs and base_share.scs and other archives to extra archives:
> ![image](https://github.com/simon50keda/ConverterPIXWrapper/assets/5429225/858e8d2b-33a7-4385-997e-56eacfb03f42)
> click "Import SCS...", navigate to /vehicle/truck/volvo_fh16_2012, select truck.pmg, click Ok, here is what you should get:
> ![image](https://github.com/simon50keda/ConverterPIXWrapper/assets/5429225/bb6dd839-9b7c-458e-9699-0d6270a6dea0)
> 
> ETS2 game archives do not contain "FH12 2016 - Truck", do you import some game modification?
> 

My feedback: I followed your tips and worked perfectly, ty so much for help. 😀

**Closed** 2024-05-22 10:44 UTC

**Comment by StodgierMist** [comment] 2024-07-05 19:08
Hello! It seems like this post have been solved on May, but im still getting this problem even after updating all my scs plugins, tried another version, or even add base.scs, base_vehicle.scs and base_share.scs and other archives to extra archives, but i still keep getting this!
![image](https://github.com/simon50keda/ConverterPIXWrapper/assets/174830931/c4e4294a-9ff4-43c5-992e-f2084f2370de)

**Comment by StodgierMist** [comment] 2024-07-08 18:37
I updated my plugins again, and i still get the error! 
![image](https://github.com/simon50keda/ConverterPIXWrapper/assets/174830931/1892b8a0-8711-4f8b-b9c3-4a93079d1b3f)

**Comment by avengerx** [comment] 2024-07-08 19:24
Hello @StodgierMist!

It looks like your output sample is not reflecting the intial issue here. Notice how the other reports' first error line says "file is corrupted" which is not the case in your scenario. I believe you'd better off creating a new issue if you want help.

Your error also points to .tobj files, and says "unable to mstat", it really looks like the problem is coming from another "layer" of the input files and something completely different will need to be done in order to fix the problem (either in your end, or in the tools' end, that's what's left unanswered).

Notice you are _required_ to use tools versions matching the current version of the game (thus base files) you have installed, or you're bound to get a myriad of errors that are simply out of scope to be fixed -- another reason to open a new issue, so your report becomes actually helpful for other people having the same issue.

**Comment by StodgierMist** [comment] 2024-07-08 22:12
Hi!
Thank you! I didnt notice the fact that in the initial issue says "file is corrupted", but the thing i did match was that this was not happening before 1.50, and now i cant really import mods, i did update my tools, being those the SCS Blender Tools addon, and ConverterPIXWrapper addon. I will create a new issue!

**Comment by mwl4** [comment] 2024-07-09 11:16
@StodgierMist 

First of all, always add base.scs and other archives as base in blender. That way you will avoid issues like "Unable to mstat file".

Secondly, the main issue is this:
![image](https://github.com/simon50keda/ConverterPIXWrapper/assets/5429225/8868728c-9af5-486a-9ae0-2c91502c2b7c)
these 5 lines of warnings/errors are generated only because `/dmgs/dbmx/irizar/i8/mago/texturas/skins/14m/skin30.dds` cannot be open, because most likely it does not exist.
Check your modification files.

**Comment by StodgierMist** [comment] 2024-07-11 02:18
@mwl4 
I did add those archives as base in blender, and the skin files should exist because i didnt had any problem before 1.50, or maybe after 1.50 it breaks if the file doesnt exist? Im not sure, as i said before, i could import the file with no problem!
And the texture does exist, because as said before, i could import the model with ease and with no errors, i even have pictures of the model. The reason i want to import again the mod is because i want to re-try another way of filling some holes of parts that im editing to convert it to the Efficient version of it. Here are some ofthe pics of when i imported the model before 1.50
![image](https://github.com/simon50keda/ConverterPIXWrapper/assets/174830931/a8c0a0c6-cc62-4485-b203-8f0b0f2cea3c)
![image](https://github.com/simon50keda/ConverterPIXWrapper/assets/174830931/0c8fcf8d-2973-4010-bf1e-f63fdfa28697)
And now, after 1.50, i just cant import it!
Here is a pic using all the base files added
![image](https://github.com/simon50keda/ConverterPIXWrapper/assets/174830931/c14ea7b5-c8d6-4789-aa23-fe98b134feda)

**Comment by mwl4** [comment] 2024-07-18 07:50
@StodgierMist Is your modification somewhere available to download, so that I can check it on my computer?
